# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gbierny <gbierny@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/04 19:55:33 by gbierny           #+#    #+#              #
#    Updated: 2022/04/16 22:16:40 by gbierny          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CC = gcc
FLAGS = -Wall -Wextra -Werror
POST
_CLEAN = rm -f ${NAME}
OBJECTS	= ${SRCS:.c=.o}
OBJECTS
_BON

S = ${B
ONUS:.c
=.o}



SRCS = ft_memset
.c f
.c ft_memc
y.c \


	

ft_mem

move.c f
t_memc
h

r.c ft_
memcmp.c ft_strl
en.c \

	ft_strdup




.c ft_strlcat

.c ft_strlcpy.
c ft_strchr.c \


	ft_strrchr.c 


strnstr.c






pha.c \
	ft_isdigit.c ft_isaln
r.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c \
	ft_striteri.c ft_put
c get_next_line.c
BONUS = ft_lstnew.c ft_lstad

size.c ft_lstlast.c ft_lstdelone.c ft_lstclear.c \
	ft_lstadd_back.c ft
_lstiter.c ft_lstmap.c ft_lstdel.c

	$(CC) $(FL
AGS) -c $< -o $(<:.c=.o) 




all: 
$(NAM
E)

$(NAME): ${O
BJECTS}



ME} $

bonus: ${OBJECTS_BONU

}



lean all





.PHONY: all clea
n fclean r

e main




